### PR TITLE
Optimize output, make valid SVG, add test files

### PR DESCRIPTION
**Pull request by AmeliaBR**

### CODE REVIEW

**Comment by meyerweb** [comment]
I love your changes, except for the color-run optimization.  The project goal really was to do this one pixel at a time.  Can I accept all the changes except that, and encourage a fork with the optimization?

**Comment by AmeliaBR** [comment]
Sure, you can cherry-pick, I won't be offended!  The alpha support & responsive scaling are definitely fun additions.

That said, it was the optimization that originally got me playing with it: "Come on, you could at least group strings of matching pixels together!"

**Comment by meyerweb** [comment]
Oh, I totally get it.  Now, if only I can figure out how to pull specific commits instead of the whole package…

**Comment by AmeliaBR** [comment]
Can't help you there.  I know it can be done, and I know that it's called "cherry picking", and beyond that you can google as well as I can...

**Comment by meyerweb** [comment]
Um, yes.  I realize that.

**Comment by AmeliaBR** [comment]
By the way, @meyerweb, the "you can google as well as I can" comment was meant in a self-deprecating "I have no idea how this git thing works" tone, not a "RTFM" tone.

Looking at again, I see how it can be misread.  The perils of text-only communication.

P.S. I'm leaving my version up with the "responsive" output.  I found that part hilarious.

**Comment by meyerweb** [comment]
Agreed.  Because it turns out there are actual use cases, I’ve spawned this to a new repository that takes the problem at least semi-seriously:  https://github.com/meyerweb/px2svg.  Further contributions should be made there, and are most welcome!

I’ll most likely roll this repository back to its initial state (or something close to it), and if I can figure out a way to leave it up in a locked state, I’ll do that.

**Pull request merged**
